import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {mkdtemp, mkdir, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {once} from 'node:events';
import {createTrackerApp} from '../server.mjs';

const directory=dirname(dirname(fileURLToPath(import.meta.url)));
const dataDirectory=await mkdtemp(join(tmpdir(),'staygrounded-analysis-browser-'));
const screenshots=join(directory,'.impeccable','review','analysis');await mkdir(screenshots,{recursive:true});
const url='https://www.reddit.com/r/productivity/comments/abc123/';
const research={findings:[{title:'Test fixture: missed renewal dates',summary:'One author describes missing a renewal date when managing subscriptions in a spreadsheet. This source alone does not establish recurring demand.',sources:[{url,title:'Test fixture: original renewal discussion'}]}],landscape:[{title:'Test fixture: calendar reminders',summary:'The discussion describes using calendar reminders as a workaround. This is a user-reported workflow, rather than a comparison of verified product prices.',sources:[{url,title:'Test fixture: calendar workaround discussion'}]}],people:[{handle:'fixture_reader',sourceUrl:url,excerpt:'I need subscription reminders before renewal.',problem:'Remember renewal dates.',fitReason:'A renewal reminder may help. The current need has not been confirmed.',matchType:'similar',needStatus:'subsequently_resolved',publishedAt:null,matchedCapabilityIds:['c1']}],coverage:'Scripted browser fixture, not live research. One thread inspected; comments incomplete.'};
const fit={decision:'strong_fit',summary:'The author asks for subscription reminders, a confirmed capability.',evidenceQuote:'I need subscription reminders before renewal.',matchedCapabilityIds:['c1'],limitations:'Only this collected excerpt was assessed; the publication date is unavailable.',replies:[{approach:'helpful',body:'A calendar reminder a few days before renewal can give you time to decide.'},{approach:'product',body:'Setting a reminder before renewal can help. I make QuietBoard, which sends renewal reminders.'}]};
let researchCalls=0,fitCalls=0;
const {app,store}=createTrackerApp({dataDirectory,analysisProvider:{available:true,research:async()=>{researchCalls++;return structuredClone(research);},match:async()=>{fitCalls++;return structuredClone(fit);}}});
const product=store.saveProduct({name:'QuietBoard',description:'Track subscriptions and send renewal reminders.',url:'https://quietboard.dev/',type:'website',capabilities:['Send renewal reminders.'],needs:['Remember renewal dates.'],keywords:['subscription reminders'],aliases:['QuietBoard'],exclusions:[],communities:[],monitoring:false});
store.saveProduct({name:'Other product',description:'A separate product.',url:'https://another-product.dev/',type:'website',keywords:['other tasks'],aliases:['Other product'],exclusions:[],communities:[],monitoring:false});
store.recordSearch(product.id,{items:[{url,title:'Test fixture: looking for subscription reminders',snippet:fit.evidenceQuote,reason:'Review needed: an expressed reminder need.',source:'Reddit',kind:'opportunity',author:'fixture_reader',publishedAt:null}],sources:[],searchedAt:new Date().toISOString()});
const listener=app.listen(0,'127.0.0.1');await once(listener,'listening');
const origin=`http://127.0.0.1:${listener.address().port}`;
let browser;
try {
  browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin);await page.getByRole('button',{name:'Problems',exact:true}).click();
  await page.getByText('Choose a product to explore its market.',{exact:true}).waitFor();assert.equal(await page.locator('#run-research').isVisible(),false);
  await page.getByRole('button',{name:'QuietBoard',exact:true}).click();
  await page.getByRole('button',{name:'Run research',exact:true}).click();
  await page.getByText('Research saved. Explore Problems, Landscape, and People.',{exact:true}).waitFor();
  assert.equal(researchCalls,1);await page.getByRole('heading',{name:'Test fixture: missed renewal dates',exact:true}).waitFor();
  await page.screenshot({path:join(screenshots,'desktop-problems.png'),fullPage:true});
  await page.getByRole('button',{name:'Landscape',exact:true}).click();await page.getByRole('heading',{name:'Test fixture: calendar reminders',exact:true}).waitFor();
  assert.equal(researchCalls,1,'Switching views does not call the provider');
  await page.getByRole('button',{name:'People',exact:true}).click();await page.getByText('Similar problem · Later reported resolved · Date unavailable',{exact:true}).waitFor();
  assert.equal(await page.getByRole('link',{name:'Open source discussion',exact:true}).getAttribute('href'),url);
  await page.getByRole('button',{name:'Other product',exact:true}).click();assert.equal(await page.locator('.research-result').count(),0);
  await page.getByRole('button',{name:'QuietBoard',exact:true}).click();assert.equal(await page.locator('.research-result').count(),1);
  await page.getByRole('button',{name:'Matches',exact:true}).click();await page.getByRole('button',{name:'Analyze fit & replies',exact:true}).click();
  await page.getByText('Fit assessment and reply suggestions saved.',{exact:true}).waitFor();assert.equal(fitCalls,1);
  await page.getByRole('heading',{name:'Strong fit',exact:true}).waitFor();assert.equal(await page.locator('.fit-analysis textarea').count(),2);
  await page.getByLabel('Helpful reply',{exact:true}).fill('Edited helpful reply for review.');
  await page.getByRole('button',{name:'Copy reply',exact:true}).first().click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'Edited helpful reply for review.');
  await page.locator('.match').getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Saved 1',exact:true}).click();
  assert.equal(await page.getByLabel('Helpful reply',{exact:true}).inputValue(),'Edited helpful reply for review.','Edits survive local rerender');
  await page.reload();await page.getByRole('button',{name:'QuietBoard',exact:true}).click();await page.getByRole('button',{name:'Saved 1',exact:true}).click();
  await page.getByText('Fit assessment & reply suggestions',{exact:true}).click();assert.equal(fitCalls,1);assert.equal(await page.getByLabel('Helpful reply',{exact:true}).inputValue(),fit.replies[0].body);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:join(screenshots,'desktop-replies.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:join(screenshots,'mobile-replies.png'),fullPage:true});
  await page.getByRole('button',{name:'People',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:join(screenshots,'mobile-people.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,researchCalls,fitCalls,screenshots,covers:['product scoping','research views','resolution labels','editable copied replies','cached results on reload','review decisions','desktop/mobile overflow','no browser errors']}));
} finally {await browser?.close();await new Promise(resolve=>listener.close(resolve));await rm(dataDirectory,{recursive:true,force:true});}
