import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createTrackerApp } from '../server.mjs';

const directory=dirname(dirname(fileURLToPath(import.meta.url)));
const dataDirectory=await mkdtemp(join(tmpdir(),'product-tracker-browser-'));
const screenshots=join(directory,'.impeccable','review');
await mkdir(screenshots,{recursive:true});
let calls=0;
const {app,store}=createTrackerApp({dataDirectory,linkedinAvailable:true,metadataFn:async url=>({url,name:'Pilot',description:'A habit tracker for daily routines.',type:'website'}),profileFn:async()=>({capabilities:['A habit tracker for daily routines.'],needs:['Keep track of daily habits.'],keywords:['habit tracking','daily routine'],communities:['habits'],message:'Scripted profile suggestions for browser testing.'}),redditAdapter:{list:async()=>({rows:[{}]})},discoverFn:async product=>{
  calls++;
  const at=new Date().toISOString();
  return {searchedAt:at,sources:[{name:'Hacker News',status:'ok',count:1,message:'Scripted test fixture, not live discovery.',queries:[{label:'Search habit tracking',url:'https://hn.algolia.com/?q=habit%20tracking'}]},{name:'LinkedIn',status:'ok',count:1,message:'Scripted LinkedIn fixture. Coverage is partial.',queries:[{label:'Search habit tracking',url:'https://www.linkedin.com/search/results/content/?keywords=habit%20tracking'}]},{name:'Reddit',status:'error',message:'Scripted blocked-source fixture.',queries:[{label:'Search Reddit',url:'https://www.reddit.com/search/?q=habit%20tracking'}]}],items:[
    {title:'Test fixture: looking for a way to keep track of daily habits',snippet:'I need help with habit tracking. My spreadsheet is difficult to keep up with.',url:'https://www.linkedin.com/posts/demo-person_habits-share-7507254982996332545-AbCd',source:'LinkedIn',provider:'linkedin-mcp',sourceId:'li_7507254982996332545',postId:'7507254982996332545',type:'post',kind:'opportunity',matchedTerms:['habit tracking'],reason:'Review needed: habit tracking appears near a request for help.',publishedAt:at},
    {title:'Test fixture: Pilot helped me build a consistent routine',snippet:'I tried Pilot for habit tracking and have been using it every day.',url:'https://news.ycombinator.com/item?id=10000002',source:'Hacker News',kind:'mention',matchedTerms:['Pilot'],reason:'Review needed: the exact product name Pilot appears in this source.',publishedAt:at}
  ]};
}});
const server=app.listen(0,'127.0.0.1');
await new Promise(resolve=>server.once('listening',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin);
  await page.getByRole('heading',{name:'Track something you built'}).waitFor();
  await page.locator('#add-product').click();
  await page.locator('#product-url').fill('https://pilot.dev');
  await page.getByRole('button',{name:'Import details from link'}).click();
  await page.getByText('Details imported. Check them').waitFor();
  await page.getByRole('button',{name:'Review tracking',exact:true}).click();
  await page.getByText('Scripted profile suggestions for browser testing.').waitFor();
  assert.equal(await page.locator('#product-linkedin').isChecked(),true);
  assert.equal(await page.locator('#product-linkedin').isDisabled(),false);
  assert.equal(await page.locator('#product-capabilities').inputValue(),'A habit tracker for daily routines.');
  assert.equal(await page.locator('#product-communities').inputValue(),'habits');
  await page.getByText('Recent public posts retrieved.',{exact:false}).waitFor();
  await page.locator('#product-keywords').fill('habit tracking\ndaily routine');
  await page.locator('#product-communities').fill('https://reddit.com/r/habits');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByText('Use up to 10 subreddit names, without links or spaces.').waitFor();
  await page.locator('#product-communities').fill('r/Habits');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  assert.equal(await page.locator('#product-monitoring').isChecked(),true);
  assert.match(await page.locator('#monitoring-help').textContent(),/Reddit runs hourly; LinkedIn runs at 8 a.m. and 8 p.m. Pacific/);
  await page.getByRole('button',{name:'Start tracking',exact:true}).click();
  await page.getByText('Search finished. Review the matches').waitFor();
  assert.equal(await page.locator('.match').count(),2);
  assert.equal(calls,1);
  assert.deepEqual(store.data.products[0].communities,['habits']);
  assert.equal(store.data.products[0].monitoring,true);
  assert.equal(store.data.products[0].linkedin,true);
  assert.match(await page.locator('#tracking-summary').textContent(),/LinkedIn posts/);
  assert.match(await page.locator('#tracking-summary').textContent(),/subreddit hourly/);
  assert.match(await page.locator('#tracking-summary').textContent(),/8 a.m. \/ 8 p.m. Pacific/);
  await page.locator('#coverage').evaluate(element=>{element.open=true;});
  await page.getByText('LinkedIn: Checked · 1 matches',{exact:true}).waitFor();
  assert.deepEqual(store.data.products[0].needs,['Keep track of daily habits.']);
  await page.locator('#kind-filter').selectOption('opportunity');
  assert.equal(await page.locator('.match').count(),1);
  await page.locator('.match').getByRole('button',{name:'Save',exact:true}).click();
  await page.getByText('Review status saved.').waitFor();
  await page.getByRole('button',{name:'Saved 1',exact:true}).click();
  await page.getByText('Add a note',{exact:true}).click();
  await page.locator('.match textarea').fill('Useful fit. Check whether the existing workflow is still a problem.');
  await page.getByRole('button',{name:'Save note',exact:true}).click();
  await page.getByText('Note saved.',{exact:true}).waitFor();
  await page.reload();
  await page.getByRole('button',{name:'Saved 1',exact:true}).waitFor();
  await page.getByRole('button',{name:'Saved 1',exact:true}).click();
  await page.getByText('Notes (saved)',{exact:true}).click();
  assert.equal(await page.locator('.match textarea').inputValue(),'Useful fit. Check whether the existing workflow is still a problem.');
  await page.getByRole('button',{name:'Find matches',exact:true}).click();
  await page.getByText('Search finished. Review the matches').waitFor();
  assert.equal(store.data.items.find(i=>i.kind==='opportunity').status,'saved');
  assert.equal(calls,2);
  await page.locator('#text-filter').fill('no such discussion');
  await page.getByRole('heading',{name:'No matches for these filters'}).waitFor();
  await page.locator('#text-filter').fill('');
  await page.getByRole('button',{name:'New 1',exact:true}).click();
  await page.locator('#kind-filter').selectOption('mention');
  await page.locator('.match').getByRole('button',{name:'Dismiss',exact:true}).click();
  await page.getByText('Review status saved.').waitFor();
  await page.getByRole('button',{name:'Dismissed 1',exact:true}).click();
  await page.getByRole('button',{name:'Restore to New',exact:true}).click();
  await page.getByText('Review status saved.').waitFor();
  await page.getByRole('button',{name:'New 1',exact:true}).click();
  await page.locator('#kind-filter').selectOption('all');
  await page.getByRole('button',{name:'Edit Pilot',exact:true}).click();
  await page.locator('#product-description').fill('A simple habit tracker that helps people maintain daily routines.');
  await page.getByRole('button',{name:'Review tracking',exact:true}).click();
  await page.locator('#setup-profile').waitFor({state:'visible'});
  assert.equal(await page.locator('#product-linkedin').isChecked(),true);
  await page.locator('#product-linkedin').uncheck();
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.locator('#product-monitoring').uncheck();
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.getByText('Product saved.',{exact:true}).waitFor();
  assert.equal(calls,2,'Editing a product does not silently trigger discovery');
  assert.equal(store.data.products[0].monitoring,false,'Pausing monitoring persists');
  assert.equal(store.data.products[0].linkedin,false,'Pausing LinkedIn persists');
  await page.locator('#coverage').evaluate(e=>e.open=false);
  await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
  await page.screenshot({path:join(screenshots,'desktop.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
  await page.waitForTimeout(150);
  await page.screenshot({path:join(screenshots,'mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No horizontal overflow on mobile');
  await page.getByRole('button',{name:'Edit Pilot',exact:true}).click();
  await page.getByRole('button',{name:'Review tracking',exact:true}).click();
  await page.locator('#setup-profile').waitFor({state:'visible'});
  await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
  await page.screenshot({path:join(screenshots,'mobile-form.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No horizontal overflow in the mobile form');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:join(screenshots,'desktop-form.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No horizontal overflow in the desktop form');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,browser:'Chrome',screenshots,covers:['website import','add and search','opportunity/mention filters','save/dismiss/restore','notes and page reload','repeat searches','edit without searching','desktop/mobile overflow','no browser errors']}));
} finally {
  await browser?.close();
  await new Promise(resolve=>server.close(resolve));
  await rm(dataDirectory,{recursive:true,force:true});
}
