import {cafe,breakdown} from './business-profile.fixture.mjs';
import {validateProduct} from '../server.mjs';
export const v2Business=()=>validateProduct({...cafe,profileVersion:'v2',businessProfileV2:{...breakdown(),reviewed:true}});
export const plan=()=>({themes:[{id:'lunch',title:'Find a croissant sandwich',need:'Find a sandwich for lunch in Vancouver',purposes:['potential_customer','feedback'],offeringIds:['o1'],keywords:['croissant sandwich','Vancouver lunch'],longTail:['Where can I get a croissant sandwich in Vancouver?'],queries:[{id:'q1',platform:'reddit',community:'vancouver',query:'croissant sandwich'},{id:'q2',platform:'reddit',community:'vancouver',query:'sandwich lunch pickup'}]}],limitations:['Community suggestions are not verified.']});
export function conversations(){return [1,2,3,4].map((n)=>({source:'Reddit',type:'post',provider:'scrapebadger',postId:`t3_cafe${n}`,sourceId:`t3_cafe${n}`,parentId:null,url:`https://www.reddit.com/r/vancouver/comments/cafe${n}/`,title:['Croissant sandwich for lunch?','Where can I get a croissant sandwich?','Recommendations for a sandwich to pick up?','Lunch delivery is frustrating'][n-1],snippet:n===4?'I wish a cafe would deliver a sandwich to my office.':['I am looking for a croissant sandwich for lunch in Vancouver.','Any Vancouver cafes with a croissant sandwich? I want one for lunch.','I need somewhere in Vancouver to pick up a croissant sandwich at lunchtime.'][n-1],author:`fixture_author_${n}`,publishedAt:new Date(Date.now()-n*86400000).toISOString(),commentCount:0,discussionClosed:n===3}));}
export function stageValue(stage,input){
 if(stage==='search_plan')return plan();
 if(stage==='qualify')return {results:input.evidence.map(e=>({evidenceId:e.id,relevant:true,directFit:!e.text.includes('deliver'),category:e.text.includes('deliver')?'complaint':'question',need:e.text.includes('deliver')?'Get a sandwich delivered':'Find a croissant sandwich for lunch',quote:e.text,offeringIds:e.text.includes('deliver')?[]:['o1'],reason:e.text.includes('deliver')?'Relevant delivery complaint; this cafe is pickup only.':'The cafe serves the requested sandwich in Vancouver.',resolved:'unknown',purposes:[{purpose:'feedback',quote:e.text,reason:'Concrete lunch need connected to the cafe offering.',offeringIds:['o1'],reference:''},...(!e.text.includes('deliver')&&!e.discussionClosed?[{purpose:'potential_customer',quote:e.text,reason:'Explicit lunch need with supported local offering.',offeringIds:['o1'],reference:''}]:[])]}))};
 if(stage==='insights')return {insights:[{id:'sandwiches',kind:'repeated_question',title:'People ask where to get croissant sandwiches',outcome:'Find a croissant sandwich for lunch in Vancouver',community:'vancouver',evidenceIds:input.evidence.filter(e=>e.qualification.category==='question').map(e=>e.id),explanation:'Three independent conversations ask for the same lunch outcome.',offeringIds:['o1'],unknowns:['Availability and current menus need checking.']},{id:'delivery',kind:'complaint',title:'Delivery is a requested convenience',outcome:'Get a sandwich delivered',community:'vancouver',evidenceIds:input.evidence.filter(e=>e.qualification.category==='complaint').map(e=>e.id),explanation:'One person wants delivery, which the cafe does not offer.',offeringIds:[],unknowns:[]}],limitations:['Bounded fixture sample; not community-wide frequency.']};
 if(stage==='actions')return {actions:[{id:'guide',insightId:'sandwiches',type:'fresh_post',title:'A practical lunch pickup checklist',reason:'A guide can help people compare nearby lunch options.',usefulAddition:'Explain how to compare menus, pickup distance and timing.',evidenceIds:input.insights[0].evidenceIds,offeringIds:['o1'],targetEvidenceId:null,community:'vancouver',affiliation:'I work with Fixture Cafe.'}],limitations:['Check community rules before posting.']};
 if(stage==='drafts')return {drafts:[{actionId:'guide',title:'A few things to check before picking up lunch',body:'Start with the menus of cafes near your pickup route and check their current hours. Compare the sandwich options and allow time for the walk. I work with Fixture Cafe. We serve croissant sandwiches for pickup in Vancouver, so that is another option if it fits your route.',reviewNotes:['Check current menus and community rules before posting.']}]};
 throw Error('Unexpected fixture stage');
}
export const pipelineProvider=()=>({available:true,run:async(stage,input)=>({value:stageValue(stage,input),model:'fixture-sol',costMicroUsd:1000})});
