import {useCallback,useEffect,useId,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {api,date,safeURL,sourceLabel} from './api';
import {canEditCollected,collectedReviewBody} from './review-state.mjs';
import './collected-conversations.css';
const analysisLabel=value=>({awaiting_analysis:'Awaiting AI analysis',analysis_failed:'AI analysis needs attention',analyzed:'Analyzed'})[value]||'Analysis status unavailable';
export function CollectedConversations({productId,state,action,busy,buffers,setBuffer}){
 const [result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[platform,setPlatform]=useState('all');
 const load=useCallback(async(signal)=>{setLoading(true);setError(null);try{const params=new URLSearchParams({relevance:'collected',productId,query:search,status,platform,offset:String(offset),limit:'50'});const next=await api(`/conversations?${params}`,{signal});if(!signal?.aborted)setResult(next);}catch(error){if(!signal?.aborted)setError(error);}finally{if(!signal?.aborted)setLoading(false);}},[productId,search,status,platform,offset]);
 useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[load]);
 return <section className="pipeline-section collected-conversations"><div className="pipeline-section-heading"><div><h2>Collected conversations</h2><p>Read keyword and long-tail results as they arrive, including ambiguous names and other businesses. Mentions shows confirmed references to your business. AI intent analysis follows its own schedule.</p></div><Button variant="outline" disabled={loading} onClick={()=>load()}>Refresh collected</Button></div><form className="collected-filters" onSubmit={event=>{event.preventDefault();setOffset(0);setSearch(query);}}><label>Search collected text<Input value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/></label><label>Conversation status<select value={status} onChange={e=>{setOffset(0);setStatus(e.target.value);}}>{[['all','All conversations'],['awaiting_analysis','Awaiting AI analysis'],['analysis_failed','Analysis needs attention'],['analyzed','Analyzed'],['new','New'],['saved','Saved'],['dismissed','Dismissed']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Source<select value={platform} onChange={e=>{setOffset(0);setPlatform(e.target.value);}}>{[['all','All sources'],['reddit','Reddit'],['x','X'],['linkedin','LinkedIn'],['tiktok','TikTok'],['instagram','Instagram'],['other','Other']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><Button variant="outline" disabled={loading}>Search collected</Button></form>
 {error&&<p role="alert" className="pipeline-notice">{error.message} <Button variant="outline" onClick={()=>load()}>Retry conversations</Button></p>}{loading?<p role="status">Loading collected conversations…</p>:result&&<><p className="muted" role="status">{result.total.toLocaleString()} conversations{result.items.length?` · Showing ${result.offset+1}–${result.offset+result.items.length}`:''}</p>{result.items.length?result.items.map(row=><CollectedRow key={row.id} row={row} editable={canEditCollected(state,row)} accountMode={Boolean(state.account)} buffered={buffers[`collected:${row.id}`]} setBuffered={value=>setBuffer(`collected:${row.id}`,value)} busy={busy} save={operation=>action(`collected-${row.id}`,async()=>{await operation();await load();},'Conversation review saved')} reload={()=>load()}/>):<p className="muted">No collected conversations match these filters.</p>}<div className="pipeline-controls"><Button variant="outline" disabled={loading||result.offset===0} onClick={()=>setOffset(Math.max(0,result.offset-50))}>Previous 50</Button><Button variant="outline" disabled={loading||!result.hasMore} onClick={()=>setOffset(result.nextOffset)}>Next 50</Button></div></>}
 </section>;
}
function CollectedRow({row,editable,accountMode,buffered,setBuffered,busy,save,reload}){
 const [error,setError]=useState(null);const formId=useId();const current=buffered||{note:row.note||'',draft:row.draft||'',status:row.status||'new',version:row.review?.version||0};
 function edit(key,value){setBuffered({...current,[key]:value});}
 return <details className="evidence-row collected-row"><summary>{row.title||'Conversation'}<span>{row.entityMention?'Confirmed mention':row.keywordMention?'Name match · identity unconfirmed':'Collected result'} · {analysisLabel(row.analysisStatus)} · {row.status||'new'}</span></summary><p className="muted">{sourceLabel(row)} · {row.author||'Author unavailable'} · {date(row.publishedAt)}</p>{row.context&&<details><summary>Discussion context</summary><p className="collected-original">{row.context}</p></details>}<p className="collected-original">{row.snippet||'Original text unavailable.'}</p>{safeURL(row.url)&&<a href={safeURL(row.url)} target="_blank" rel="noreferrer">Open original conversation</a>}
 <details className="collected-review"><summary>Notes, status and saved draft{buffered?' · Unsaved changes':''}</summary>{!editable&&<p className="muted">{row.reviewEditable===false?'This older source record is read-only until it is added to the review store.':'You have read-only access to this workspace.'}</p>}<form onSubmit={event=>{event.preventDefault();save(async()=>{setError(null);try{await api(`/items/${encodeURIComponent(row.id)}`,{method:'PATCH',body:collectedReviewBody(current,accountMode)});setBuffered(undefined);}catch(error){setError(error);throw error;}});}}><fieldset disabled={!editable||!!busy}><div><label htmlFor={`${formId}-status`}>Review status</label><select id={`${formId}-status`} value={current.status} onChange={e=>edit('status',e.target.value)}><option value="new">New</option><option value="saved">Saved</option><option value="dismissed">Dismissed</option></select></div><div><label htmlFor={`${formId}-note`}>Your note</label><Textarea id={`${formId}-note`} value={current.note} maxLength={3000} onChange={e=>edit('note',e.target.value)}/></div><div><label htmlFor={`${formId}-draft`}>Saved draft</label><Textarea id={`${formId}-draft`} value={current.draft} maxLength={5000} onChange={e=>edit('draft',e.target.value)}/></div><div className="pipeline-controls"><Button disabled={!buffered}>Save review</Button>{buffered&&<Button type="button" variant="outline" onClick={()=>{if(confirm('Discard these unsaved review changes and load the latest version?')){setBuffered(undefined);setError(null);reload();}}}>Discard and reload</Button>}</div></fieldset></form>{error&&<p role="alert" className="pipeline-notice">{error.message} Your unsaved changes are still available.</p>}</details></details>;
}
