import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {planIntervals,cadenceLabel} from './plan-timing.mjs';
import {api,lines} from './api';
import {BusinessProfileBreakdown,breakdownMatches} from './BusinessProfileBreakdown';
const listKeys=['capabilities','needs','communities','keywords','aliases','exclusions','xQueries'];
export function ProductEditor({open,onOpenChange,product,state,onSaved,onDeleted}){
 const [step,setStep]=useState(1),[values,setValues]=useState(()=>({...Object.fromEntries(['name','url','description',...listKeys].map(k=>[k,Array.isArray(product?.[k])?product[k].join('\n'):product?.[k]||''])),profileVersion:'v2',profileV1:product?.profileV1||{capabilities:product?.capabilities||[],needs:product?.needs||[]},businessProfileV2:product?.businessProfileV2||null,monitoring:product?Boolean(product.monitoring):Boolean(state.monitoring?.available),x:product?product.x!==false:Boolean(state.sources?.x?.available),linkedin:Boolean(product?.linkedin)})),[busy,setBusy]=useState(''),[error,setError]=useState(''),[checks,setChecks]=useState([]);
 const set=(key,value)=>setValues(v=>({...v,[key]:value}));
 async function run(name,fn){setBusy(name);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy('');}}
 function input(){return {...values,...Object.fromEntries(listKeys.map(k=>[k,lines(values[k])])),profileV1:values.profileV1,communities:lines(values.communities).map(s=>s.replace(/^r\//i,'').toLowerCase())};}
 async function generateBreakdown(){await run('breakdown',async()=>{const r=await api('/profile',{method:'POST',body:{version:'v2',name:values.name,url:values.url,description:values.description,refresh:Boolean(values.businessProfileV2)}});setValues(v=>({...v,businessProfileV2:r.profile}));});}

 async function save(e){e.preventDefault();if(step!==3||busy)return;if(values.profileVersion==='v2'&&(!values.businessProfileV2?.reviewed||!breakdownMatches(values.businessProfileV2,values))){setError('Refresh and review your business breakdown before saving.');setStep(2);return;}await run('save',async()=>{const body=input();const r=await api(product?`/products/${product.id}`:'/products',{method:product?'PUT':'POST',body});await onSaved(r.product);});}
 const field=(key,label,{long=false,help='',max=5000,required=false,rows=3}={})=><div><label htmlFor={`product-${key}`}>{label}</label>{long?<Textarea id={`product-${key}`} value={values[key]} onChange={e=>set(key,e.target.value)} maxLength={max} rows={rows} required={required}/>:<Input id={`product-${key}`} value={values[key]} onChange={e=>set(key,e.target.value)} maxLength={max} required={required} type={key==='url'?'url':'text'}/>} {help&&<p className="field-help">{help}</p>}</div>;
 return <Dialog open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><DialogContent className="product-dialog"><DialogHeader><DialogTitle>{product?'Edit product':'Add product'}</DialogTitle><DialogDescription>{step===1?'Start with your website or App Store page.':step===2?'Confirm the features and conversations that matter.':'Choose where and how often to look for conversations.'}</DialogDescription></DialogHeader><form onSubmit={save} className="product-form"><fieldset disabled={!!busy}>
  <p className="setup-step">Step {step} of 3 · {['Product details','Tracking profile','Sources and monitoring'][step-1]}</p>
  {step===1&&<div className="form-fields">{field('url','Website or App Store URL',{max:2048,required:true})}<Button type="button" variant="outline" onClick={()=>run('import',async()=>{const r=await api('/metadata',{method:'POST',body:{url:values.url}});setValues(v=>({...v,url:r.url,name:r.name||v.name,description:r.description||v.description,aliases:v.aliases||r.name||''}));})}>{busy==='import'?'Importing…':'Import details from link'}</Button>{field('name','Product name',{max:120,required:true})}{field('description','What does it do?',{long:true,required:true,rows:5})}</div>}
  {step===2&&<div className="form-fields"><BusinessProfileBreakdown profile={values.businessProfileV2} onChange={value=>set('businessProfileV2',value)} onGenerate={generateBreakdown} busy={busy==='breakdown'} available={state.businessProfiles?.v2Available} current={breakdownMatches(values.businessProfileV2,values)}/>{field('keywords','Search phrases',{long:true,required:true,help:'Starting phrases, one per line. Review the full search plan in Settings → Monitoring.'})}<details><summary>Names and exclusions</summary><div className="form-fields">{field('aliases','Product names and aliases',{long:true})}{field('exclusions','Exclude these phrases',{long:true})}</div></details></div>}
  {step===3&&<div className="form-fields">{field('communities','Reddit communities',{long:true,help:'One subreddit name per line, up to 10. No links needed.'})}<Button type="button" variant="outline" onClick={()=>run('communities',async()=>{const r=await api('/communities/check',{method:'POST',body:{communities:input().communities}});setChecks(r.checks||[]);})}>{busy==='communities'?'Checking…':'Check communities'}</Button>{checks.length>0&&<ul className="community-checks">{checks.map((c,i)=><li key={i}>r/{c.name}: {c.message||c.status}</li>)}</ul>}<label className="check-field"><input type="checkbox" checked={values.x} disabled={!state.sources?.x?.available&&!values.x} onChange={e=>set('x',e.target.checked)}/><span>Include X</span></label>{values.x&&field('xQueries','X search queries (optional)',{long:true,help:'Up to two queries. Leave blank to use your search phrases.'})}<label className="check-field"><input type="checkbox" checked={values.linkedin} disabled={!state.sources?.linkedin?.available&&!values.linkedin} onChange={e=>set('linkedin',e.target.checked)}/><span>Include LinkedIn</span></label><label className="check-field"><input type="checkbox" checked={values.monitoring} disabled={!state.monitoring?.available&&!values.monitoring} onChange={e=>set('monitoring',e.target.checked)}/><span>{planIntervals(state,product?.id)?`Check for new keyword matches ${cadenceLabel(planIntervals(state,product?.id).keyword).toLowerCase()}`:'Check for new Reddit and X conversations every two hours'}</span></label><p className="field-help">New products also receive separate past-year searches across configured sources. Google discovery and business reviews run daily. LinkedIn checks run at 8 a.m. and 8 p.m. Pacific when enabled.</p>{product&&<p className="field-help">Changing features or search terms can stop an active historical plan; its progress and existing matches are retained.</p>}</div>}
 </fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<DialogFooter><Button type="button" variant="outline" disabled={!!busy} onClick={()=>step>1?setStep(step-1):onOpenChange(false)}>{step>1?'Back':'Cancel'}</Button>{step<3?<Button type="button" variant={step===2&&(!values.businessProfileV2?.reviewed||!breakdownMatches(values.businessProfileV2,values))?'outline':'default'} disabled={!!busy} onClick={e=>{e.preventDefault();if(step===1&&(!values.name.trim()||!values.url.trim()||!values.description.trim())){setError('Enter the product name, URL, and description.');return;}if(step===2&&(!values.businessProfileV2?.reviewed||!breakdownMatches(values.businessProfileV2,values))){setError('Generate and review your business breakdown to continue.');return;}if(step===2&&!lines(values.keywords).length){setError('Add at least one search phrase to continue.');return;}setError('');setStep(step+1);}}>Continue</Button>:<Button type="submit" disabled={!!busy}>{busy==='save'?'Saving…':product?'Save changes':'Start tracking'}</Button>}</DialogFooter>{product&&<Button type="button" variant="ghost" className="delete-product" disabled={!!busy} onClick={()=>{if(confirm(`Delete ${product.name} and its saved conversations?`))run('delete',async()=>{await api(`/products/${product.id}`,{method:'DELETE',body:{}});await onDeleted();});}}>Delete product</Button>}</form></DialogContent></Dialog>;
}
