import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {addMedia,removeMedia,mediaBlob} from './video-media.mjs';

export function VideoMediaLibrary({scope,library,onChange,disabled}){
 const [kind,setKind]=useState('clip'),[mode,setMode]=useState('original'),[label,setLabel]=useState(''),[description,setDescription]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[clean,setClean]=useState(false),[file,setFile]=useState(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(null);
 const input=useRef(null),activePreview=useRef(null);
 useEffect(()=>()=>{if(activePreview.current)URL.revokeObjectURL(activePreview.current);},[]);
 function closePreview(){if(activePreview.current)URL.revokeObjectURL(activePreview.current);activePreview.current=null;setPreview(null);}
 async function add(){
  setError('');setPending(true);
  try{if(!file)throw new Error('Choose a media file.');if(library.filter(row=>row.kind===kind).length>=12)throw new Error(`Keep up to twelve ${kind==='clip'?'clips':'backgrounds'} in this library.`);const saved=await addMedia(scope,file,{kind,mode,label,description,sourceUrl,clean});onChange([...library,saved]);setFile(null);setLabel('');setDescription('');setSourceUrl('');setClean(false);if(input.current)input.current.value='';}
  catch(error){setError(error.message);}finally{setPending(false);}
 }
 return <details className="video-media-library"><summary>Clips & backgrounds <span>{library.filter(row=>row.kind==='clip').length} clips · {library.filter(row=>row.kind==='background').length} backgrounds</span></summary>
  <p className="muted">Import a clean file and describe what happens in it. Files stay in this browser; the writing model receives your descriptions.</p>
  <div className="video-library-grid">{['clip','background'].map(type=><section key={type}><h3>{type==='clip'?'Reaction clips':'Background images'}</h3>{library.filter(row=>row.kind===type).map(row=><div className="video-library-row" key={row.id}><div><strong>{row.label}</strong><p>{row.description}</p><small>{type==='clip'?`${row.duration.toFixed(1)}s · ${row.mode==='green'?'Green screen':'Original background'}`:`${row.width} × ${row.height}`}</small></div><div><Button size="sm" variant="ghost" onClick={async()=>{closePreview();const blob=await mediaBlob(scope,row.id);if(!blob){setError('The file is missing from this browser. Import it again.');return;}const url=URL.createObjectURL(blob);activePreview.current=url;setPreview({url,...row});}}>View</Button><Button size="sm" variant="ghost" disabled={disabled||pending} onClick={async()=>{try{await removeMedia(scope,row.id);onChange(library.filter(asset=>asset.id!==row.id));closePreview();}catch(error){setError(error.message);}}}>Remove</Button></div></div>)}{!library.some(row=>row.kind===type)&&<p className="muted">{type==='clip'?'No clips imported yet.':'A plain background is available without an image.'}</p>}</section>)}</div>
  {preview&&<div className="video-library-preview">{preview.kind==='clip'?<video src={preview.url} controls playsInline/>:<img src={preview.url} alt={preview.description}/>}<Button variant="ghost" size="sm" onClick={closePreview}>Close preview</Button></div>}
  {!disabled&&<div className="video-media-import"><div className="video-media-import-fields"><label className="video-field">Asset type<select value={kind} disabled={pending} onChange={event=>{setKind(event.target.value);setFile(null);setClean(false);if(input.current)input.current.value='';}}><option value="clip">Reaction clip</option><option value="background">Background image</option></select></label>{kind==='clip'&&<label className="video-field">Clip background<select value={mode} disabled={pending} onChange={event=>setMode(event.target.value)}><option value="original">Keep original background</option><option value="green">Remove green screen</option></select></label>}<label className="video-field">Asset name<Input value={label} maxLength={120} disabled={pending} onChange={event=>setLabel(event.target.value)}/></label></div>
   <label className="video-field">{kind==='clip'?'What happens in this clip?':'What does this background show?'}<Textarea value={description} rows={2} maxLength={500} disabled={pending} placeholder={kind==='clip'?'Describe the action in order, its timing, and the payoff. Include any known meme meaning.':'Describe the setting and when it makes sense to use it.'} onChange={event=>setDescription(event.target.value)}/></label><label className="video-field">Source URL (optional)<Input value={sourceUrl} maxLength={2048} disabled={pending} onChange={event=>setSourceUrl(event.target.value)}/></label><label className="video-field">{kind==='clip'?'Clip file':'Background file'}<input ref={input} type="file" accept={kind==='clip'?'video/mp4,video/webm,video/quicktime':'image/png,image/jpeg,image/webp'} disabled={pending} onChange={event=>{setFile(event.target.files?.[0]||null);setClean(false);}}/></label>
   <label className="video-media-check"><input type="checkbox" checked={clean} disabled={pending} onChange={event=>setClean(event.target.checked)}/> I checked this file: it has no burned-in captions.</label><Button variant="outline" disabled={pending||!file||!clean||!label.trim()||description.trim().length<20} onClick={add}>{pending?'Importing…':`Add ${kind==='clip'?'clip':'background'}`}</Button>
  </div>}{error&&<p role="alert" className="form-error">{error}</p>}
 </details>;
}
