import {toast} from 'sonner';
import {Check,LoaderCircle,Pause} from 'lucide-react';
import {feedProgress} from './progress.mjs';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {api,date} from './api';
import {planIntervals,cadenceLabel,monitoringTiming} from './plan-timing.mjs';
const dollars=n=>'$'+((n||0)/1e6).toFixed(4);
export function CollectionProgress({state,products,action,busy}){
 if(!products.length)return null;
 const progress=feedProgress(state,products),Icon=progress.phase==='finding'?LoaderCircle:progress.phase==='paused'?Pause:Check;
 const jobs=products.flatMap(p=>state.collection?.backfills?.[p.id]?[{p,j:state.collection.backfills[p.id]}]:[]);
 return <section className="discovery-progress" aria-label="Conversation updates">
  <p className={`discovery-status ${progress.phase}`} role="status" aria-live="polite" aria-atomic="true"><Icon aria-hidden="true" className={progress.phase==='finding'?'spin':''}/><span>{progress.message}</span></p>
  {progress.partial&&progress.phase!=='finding'&&<p className="discovery-coverage">Some searches reached their limit. More conversations may exist.</p>}
  {state.collection&&<details className="collection-progress"><summary>Search coverage</summary><div className="coverage-details">
   {jobs.map(({p,j})=><section key={p.id}><h3>{p.name}</h3><p>Past-year search · {date(j.from)}–{date(j.to)}</p><p>{['running','reviewing'].includes(j.status)?'Finding conversations from the past year.':'Past-year search finished.'} Earlier conversations may no longer need a reply.</p>{['reddit','x'].map(platform=>{const branches=(j.branches||[]).filter(b=>b.platform===platform);return branches.length?<details key={platform}><summary>{platform==='x'?'X':'Reddit'} · {branches.filter(b=>b.status==='searched').length}/{branches.length} searches finished</summary>{branches.map(b=><p key={b.id} className="query-record">{b.query} · {b.status==='searched'?'Finished':b.status==='failed'?'Could not finish':'In progress'}</p>)}</details>:null;})}{j.errors?.length>0&&<p className="muted">Some searches could not cover every conversation.</p>}</section>)}
   {products.filter(p=>!state.collection.backfills?.[p.id]).map(p=><section key={p.id}><h3>{p.name}</h3><p>Find relevant discussions from the past 365 days.</p><Button variant="outline" disabled={!!busy} onClick={()=>action('backfill',()=>api(`/products/${p.id}/backfill`,{method:'POST',body:{}}),'Finding conversations from the past year')}>Search the past year</Button></section>)}
   <p className="muted">{monitoringTiming(state,products.length===1?products[0].id:undefined)} when monitoring is enabled. Search coverage is limited; it is not a complete archive.</p>
  </div></details>}
 </section>;
}
export function Settings({state,logout,reload,action,busy,onPurposes}){
 const file=useRef(null),[restoreError,setRestoreError]=useState(''),intervals=planIntervals(state);const q=state.qualification,b=q?.budget||{},s=state.collection?.budget||{};
 async function restore(e){const chosen=e.target.files?.[0];if(!chosen)return;setRestoreError('');try{const maxMb=state.conversationPaging?(state.storage==='cloud'?4:64):2,max=state.conversationPaging?maxMb*1024*1024:2_000_000;if(chosen.size>max)throw Error(`The backup must be under ${maxMb} MB.`);const data=JSON.parse(await chosen.text());if(!confirm('Replace current products, matches, and notes with this backup?'))return;await action('restore',()=>api('/import',{method:'POST',body:data}),'Backup restored');}catch(err){setRestoreError(err.message);}finally{e.target.value='';}}
 return <div className="settings-view">{onPurposes&&<section><h2>Purposes</h2><p>Choose which conversation views appear under HearWhispers in your sidebar.</p><Button variant="outline" onClick={onPurposes}>Manage purposes</Button></section>}<section><h2>Monitoring</h2><p>Manage search themes, sources, collection and review for the selected product.</p><Button variant="outline" asChild><a href="#settings/monitoring">Monitoring settings</a></Button></section><section><h2>Workspace</h2><dl><div><dt>Storage</dt><dd>{state.storage==='cloud'?'Private cloud workspace':'This computer'}</dd></div>{intervals?[['keyword','Keyword searches'],['long_tail','Long-tail discovery'],['analysis','AI analysis']].map(([loop,label])=><div key={loop}><dt>{label}</dt><dd>{cadenceLabel(intervals[loop])}</dd></div>):<div><dt>Regular monitoring</dt><dd>Every two hours</dd></div>}<div><dt>Qualification</dt><dd>Sol medium</dd></div></dl>{state.storage==='cloud'&&<Button variant="outline" disabled={!!busy} onClick={()=>logout().catch(e=>toast.error(e.message))}>Sign out</Button>}</section><PlanUsage state={state}/><section><h2>Daily allowances</h2><p>Shared across this workspace, reset each Pacific day.</p><dl><div><dt>Scraping</dt><dd>{(s.spentCredits||0)+(s.reservedCredits||0)} / {state.collection?.limitCredits||0} credits used or held</dd></div><div><dt>Unknown outcomes</dt><dd>{s.uncertainCredits||0} scraping credits held</dd></div><div><dt>AI review</dt><dd>{dollars((b.spentMicroUsd||0)+(b.reservedMicroUsd||0))} / {dollars(b.limitMicroUsd)} used or held</dd></div></dl>{b.paused&&<p>AI review is paused at its current allowance.</p>}<p>Scraping credits may come from free or prepaid balances. Credit usage is not necessarily a cash charge.</p></section><section><h2>AI review</h2><p>{q?.enabled?'Reviews continue in the background.':'AI review is unavailable.'} {q?.counts?.pending||0} queued · {q?.counts?.qualified||0} qualified · {q?.counts?.uncertain||0} uncertain.</p>{state.products.filter(p=>state.qualification?.products?.[p.id]?.pending).map(p=><Button variant="outline" key={p.id} disabled={!!busy||!q?.enabled||b.paused} onClick={()=>action('qualification',()=>api('/qualification/run',{method:'POST',body:{productId:p.id}}),'Review batch finished')}>Review queued posts for {p.name}</Button>)}</section><section><h2>Backup</h2><p>Export products, conversations, decisions, notes, and saved drafts.</p><div className="settings-actions"><Button variant="outline" asChild><a href="/api/export" download="hearwhispers-backup.json">Export backup</a></Button><Button variant="outline" disabled={!!busy} onClick={()=>file.current?.click()}>Restore backup</Button><input ref={file} type="file" accept="application/json,.json" hidden onChange={restore}/></div>{restoreError&&<p role="alert" className="form-error">{restoreError}</p>}</section></div>;
}

const count=value=>(value??0).toLocaleString();
function PlanUsage({state}){
 const collected=state.collection?.collectedUsage,analysis=state.usage?.analysis,aiLimit=analysis?.monthly?.limit??state.entitlements?.limits?.monthlyAiAnalyses;
 if(!collected?.monthly&&!aiLimit)return null;
 return <section><h2>Plan allowances</h2><p>Collection and AI review have separate allowances. Literal name matches appear in Mentions before AI review.</p><dl>
  {collected?.monthly&&<div><dt>Monthly collected conversations</dt><dd>{count(collected.monthly.used)} / {count(collected.monthly.limit)} collected · {count(collected.monthly.reserved)} held · {count(collected.monthly.remaining)} remaining{collected.monthly.resetAt&&<>. Resets {date(collected.monthly.resetAt)}.</>}</dd></div>}
  {aiLimit&&<div><dt>Monthly AI analyses</dt><dd>{analysis?.monthly?<>{count(analysis.monthly.used)} / {count(aiLimit)} used or held · {count(analysis.monthly.remaining)} remaining. {count(analysis.monthly.completed)} completed · {count(analysis.monthly.reserved)} reserved · {count(analysis.monthly.uncertain)} uncertain{analysis.monthly.resetAt&&<>. Resets {date(analysis.monthly.resetAt)}.</>}</>:<>{count(aiLimit)} included</>}</dd></div>}
 </dl>{(Object.keys(collected?.historical||{}).length>0||Object.keys(analysis?.historical||{}).length>0)&&<details><summary>Separate past-year allowances</summary><dl>
  {Object.entries(collected?.historical||{}).map(([id,usage])=><div key={`collection:${id}`}><dt>{state.products.find(p=>p.id===id)?.name||'Product'} · historical collection</dt><dd>{count(usage.used)} / {count(usage.limit)} collected · {count(usage.reserved)} held · {count(usage.remaining)} remaining</dd></div>)}
  {Object.entries(analysis?.historical||{}).map(([id,usage])=><div key={`analysis:${id}`}><dt>{state.products.find(p=>p.id===usage.productId)?.name||'Product'} · historical AI review</dt><dd>{count(usage.used)} / {count(usage.limit)} used or held · {count(usage.remaining)} remaining</dd></div>)}
 </dl></details>}</section>;
}
