import {toast} from 'sonner';
import {Check,LoaderCircle,Pause} from 'lucide-react';
import {feedProgress} from './progress.mjs';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {api,date,safeURL} from './api';
const dollars=n=>'$'+((n||0)/1e6).toFixed(4);
export function CollectionProgress({state,products,action,busy}){
 if(!products.length)return null;
 const progress=feedProgress(state,products),Icon=progress.phase==='finding'?LoaderCircle:progress.phase==='paused'?Pause:Check;
 const jobs=products.flatMap(p=>state.collection?.backfills?.[p.id]?[{p,j:state.collection.backfills[p.id]}]:[]);
 return <section className="discovery-progress" aria-label="Conversation updates">
  <p className={`discovery-status ${progress.phase}`} role="status" aria-live="polite" aria-atomic="true"><Icon aria-hidden="true" className={progress.phase==='finding'?'spin':''}/><span>{progress.message}</span></p>
  {progress.partial&&progress.phase!=='finding'&&<p className="discovery-coverage">Some searches reached their limit. More conversations may exist.</p>}
  {state.collection&&<details className="collection-progress"><summary>Search coverage</summary><div className="coverage-details">
   {jobs.map(({p,j})=><section key={p.id}><h3>{p.name}</h3><p>Past-year search · {date(j.from)}–{date(j.to)}</p><p>{['running','reviewing'].includes(j.status)?'Finding conversations from the past year.':'Past-year search finished.'} Earlier conversations may no longer need a reply.</p>{['reddit','x'].map(platform=>{const branches=(j.branches||[]).filter(b=>b.platform===platform);return branches.length?<details key={platform}><summary>{platform==='x'?'X':'Reddit'} · {branches.filter(b=>b.status==='searched').length}/{branches.length} searches finished</summary>{branches.map(b=><p key={b.id} className="query-record">{b.query} · {b.status==='searched'?'Finished':b.status==='failed'?'Could not finish':'In progress'}</p>)}</details>:null;})}{j.errors?.length>0&&<p className="muted">Some searches could not cover every conversation.</p>}</section>)}
   {products.filter(p=>!state.collection.backfills?.[p.id]).map(p=><section key={p.id}><h3>{p.name}</h3><p>Find relevant discussions from the past 365 days.</p><Button variant="outline" disabled={!!busy} onClick={()=>action('backfill',()=>api(`/products/${p.id}/backfill`,{method:'POST',body:{}}),'Finding conversations from the past year')}>Search the past year</Button></section>)}
   <p className="muted">Reddit and X are checked every two hours when monitoring is enabled. Search coverage is limited; it is not a complete archive.</p>
  </div></details>}
 </section>;
}
export function Settings({state,logout,reload,action,busy}){
 const file=useRef(null),[restoreError,setRestoreError]=useState('');const q=state.qualification,b=q?.budget||{},s=state.collection?.budget||{};
 async function restore(e){const chosen=e.target.files?.[0];if(!chosen)return;setRestoreError('');try{if(chosen.size>2_000_000)throw Error('The backup must be under 2 MB.');const data=JSON.parse(await chosen.text());if(!confirm('Replace current products, matches, and notes with this backup?'))return;await action('restore',()=>api('/import',{method:'POST',body:data}),'Backup restored');}catch(err){setRestoreError(err.message);}finally{e.target.value='';}}
 return <div className="settings-view"><section><h2>Workspace</h2><dl><div><dt>Storage</dt><dd>{state.storage==='cloud'?'Private cloud workspace':'This computer'}</dd></div><div><dt>Regular monitoring</dt><dd>Every two hours</dd></div><div><dt>Qualification</dt><dd>Sol medium</dd></div></dl>{state.storage==='cloud'&&<Button variant="outline" disabled={!!busy} onClick={()=>logout().catch(e=>toast.error(e.message))}>Sign out</Button>}</section><section><h2>Daily allowances</h2><p>Shared across this workspace, reset each Pacific day.</p><dl><div><dt>Scraping</dt><dd>{(s.spentCredits||0)+(s.reservedCredits||0)} / {state.collection?.limitCredits||0} credits used or held</dd></div><div><dt>Unknown outcomes</dt><dd>{s.uncertainCredits||0} scraping credits held</dd></div><div><dt>AI review</dt><dd>{dollars((b.spentMicroUsd||0)+(b.reservedMicroUsd||0))} / {dollars(b.limitMicroUsd)} used or held</dd></div></dl>{b.paused&&<p>AI review is paused at its current allowance.</p>}<p>Scraping credits may come from free or prepaid balances. Credit usage is not necessarily a cash charge.</p></section><section><h2>AI review</h2><p>{q?.enabled?'Reviews continue in the background.':'AI review is unavailable.'} {q?.counts?.pending||0} queued · {q?.counts?.qualified||0} qualified · {q?.counts?.uncertain||0} uncertain.</p>{state.products.filter(p=>state.qualification?.products?.[p.id]?.pending).map(p=><Button variant="outline" key={p.id} disabled={!!busy||!q?.enabled||b.paused} onClick={()=>action('qualification',()=>api('/qualification/run',{method:'POST',body:{productId:p.id}}),'Review batch finished')}>Review queued posts for {p.name}</Button>)}</section><section><h2>Backup</h2><p>Export products, conversations, decisions, notes, and saved drafts.</p><div className="settings-actions"><Button variant="outline" asChild><a href="/api/export" download="hearwhispers-backup.json">Export backup</a></Button><Button variant="outline" disabled={!!busy} onClick={()=>file.current?.click()}>Restore backup</Button><input ref={file} type="file" accept="application/json,.json" hidden onChange={restore}/></div>{restoreError&&<p role="alert" className="form-error">{restoreError}</p>}</section></div>;
}
export function Research({state,productFilter,action,busy}){
 const [tab,setTab]=useState('problems'),id=productFilter==='all'?state.products[0]?.id:productFilter,record=state.research?.[id];const rows=tab==='problems'?record?.findings:tab==='landscape'?record?.landscape:record?.people;
 return <div className="research-view"><div className="research-toolbar"><Button disabled={!id||!state.analysis?.available||!!busy} variant="outline" onClick={()=>action('research',()=>api(`/products/${id}/research`,{method:'POST',body:{refresh:Boolean(record)}}),'Research saved')}>{busy==='research'?'Researching…':record?'Refresh research':'Run research'}</Button></div><p className="muted">Explore source-supported needs, alternatives, and people. Research uses the shared AI allowance when you run it.</p><div className="platform-bar">{['problems','landscape','people'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{record&&<p className="muted">Researched {date(record.generatedAt)}{record.stale?' · Product details changed; refresh the research.':''}{record.expired?' · Over 30 days old.':''} {record.coverage}</p>}{!record&&<p className="view-note">{!id?'Add a product to begin.':state.analysis?.available?'Choose Run research to explore this product’s market.':'Research is unavailable.'}</p>}{record&&!rows?.length&&<p className="view-note">The inspected sources did not provide enough evidence for this view.</p>}{rows?.map((r,i)=><article className="research-result" key={i}>{tab==='people'?<><h2>u/{r.handle}</h2><p>{r.problem}</p><blockquote>{r.excerpt}</blockquote><p>{r.fitReason}</p><p className="muted">{r.needStatus.replaceAll('_',' ')} · {date(r.publishedAt)}</p><a href={safeURL(r.sourceUrl)} target="_blank" rel="noopener noreferrer">Open discussion</a></>:<><h2>{r.title}</h2><p>{r.summary}</p><ul>{r.sources?.map((s,j)=><li key={j}><a href={safeURL(s.url)} target="_blank" rel="noopener noreferrer">{s.title}</a></li>)}</ul></>}</article>)}</div>;
}
